//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRegistry.WorkerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkerServiceReference.IWorker")]
    public interface IWorker {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorker/Dmmy", ReplyAction="http://tempuri.org/IWorker/DmmyResponse")]
        void Dmmy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorker/Dmmy", ReplyAction="http://tempuri.org/IWorker/DmmyResponse")]
        System.Threading.Tasks.Task DmmyAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkerChannel : ServiceRegistry.WorkerServiceReference.IWorker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkerClient : System.ServiceModel.ClientBase<ServiceRegistry.WorkerServiceReference.IWorker>, ServiceRegistry.WorkerServiceReference.IWorker {
        
        public WorkerClient() {
        }
        
        public WorkerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Dmmy() {
            base.Channel.Dmmy();
        }
        
        public System.Threading.Tasks.Task DmmyAsync() {
            return base.Channel.DmmyAsync();
        }
    }
}
