//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splash.SlaveWorker.Executable.ServiceRegistry {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerConnectionInfo", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial class ServerConnectionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRegistry.IRegistry")]
    public interface IRegistry {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistry/AssignServer", ReplyAction="http://tempuri.org/IRegistry/AssignServerResponse")]
        Splash.SlaveWorker.Executable.ServiceRegistry.ServerConnectionInfo AssignServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistry/AssignServer", ReplyAction="http://tempuri.org/IRegistry/AssignServerResponse")]
        System.Threading.Tasks.Task<Splash.SlaveWorker.Executable.ServiceRegistry.ServerConnectionInfo> AssignServerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistry/AssignServerId", ReplyAction="http://tempuri.org/IRegistry/AssignServerIdResponse")]
        string AssignServerId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistry/AssignServerId", ReplyAction="http://tempuri.org/IRegistry/AssignServerIdResponse")]
        System.Threading.Tasks.Task<string> AssignServerIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistry/AcknowlegdeRegistration", ReplyAction="http://tempuri.org/IRegistry/AcknowlegdeRegistrationResponse")]
        bool AcknowlegdeRegistration(string serviceId, string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistry/AcknowlegdeRegistration", ReplyAction="http://tempuri.org/IRegistry/AcknowlegdeRegistrationResponse")]
        System.Threading.Tasks.Task<bool> AcknowlegdeRegistrationAsync(string serviceId, string uri);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistryChannel : Splash.SlaveWorker.Executable.ServiceRegistry.IRegistry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistryClient : System.ServiceModel.ClientBase<Splash.SlaveWorker.Executable.ServiceRegistry.IRegistry>, Splash.SlaveWorker.Executable.ServiceRegistry.IRegistry {
        
        public RegistryClient() {
        }
        
        public RegistryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Splash.SlaveWorker.Executable.ServiceRegistry.ServerConnectionInfo AssignServer() {
            return base.Channel.AssignServer();
        }
        
        public System.Threading.Tasks.Task<Splash.SlaveWorker.Executable.ServiceRegistry.ServerConnectionInfo> AssignServerAsync() {
            return base.Channel.AssignServerAsync();
        }
        
        public string AssignServerId() {
            return base.Channel.AssignServerId();
        }
        
        public System.Threading.Tasks.Task<string> AssignServerIdAsync() {
            return base.Channel.AssignServerIdAsync();
        }
        
        public bool AcknowlegdeRegistration(string serviceId, string uri) {
            return base.Channel.AcknowlegdeRegistration(serviceId, uri);
        }
        
        public System.Threading.Tasks.Task<bool> AcknowlegdeRegistrationAsync(string serviceId, string uri) {
            return base.Channel.AcknowlegdeRegistrationAsync(serviceId, uri);
        }
    }
}
